[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "GeraFed"
version = "1.0.0"
description = "Data Augmentation para Dados Heterogêneos em Aprendizado Federado"
license = "Apache-2.0"
dependencies = [
    "flwr[simulation]>=1.12.0",
    "flwr-datasets[vision]>=0.3.0",
    "torch==2.2.1",
    "torchvision==0.17.1",
]

[tool.hatch.build.targets.wheel]
packages = ["."]

[tool.flwr.app]
publisher = "gustavoguaragna"

[tool.flwr.app.components]
serverapp = "Simulation.server_app:app"
clientapp = "Simulation.client_app:app"

[tool.flwr.app.config]
num_rodadas = 5
num_clientes = 2
tam_ruido = 100
tam_batch = 64
tam_img = 64
epocas_alvo = 2
epocas_gen = 2
num_dadossint = 10
learn_rate_alvo = 0.001
learn_rate_gen = 0.001
modelo_alvo = "mlp"
modelo_gen = "gan"
dataset = "mnist"

[tool.flwr.federations]
default = "local-simulation"

[tool.flwr.federations.local-simulation]
options.num-supernodes = 2
