[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "GeraFed"
version = "1.0.0"
description = "Data Augmentation para Dados Heterogêneos em Aprendizado Federado"
license = "Apache-2.0"
dependencies = [
    "flwr[simulation]",
    "flwr-datasets",
    "torchvision",
    "numpy<2.0",
    "xgboost",
    "ctgan"
]

[tool.hatch.build.targets.wheel]
packages = ["."]

[tool.flwr.app]
publisher = "gustavoguaragna"

[tool.flwr.app.components]
serverapp = "Simulation.server_app:app"
clientapp = "Simulation.client_app:app"

[tool.flwr.app.config]
num_rodadas = 2000
fraction_fit_alvo = 1.0
fraction_fit_gen = 1.0
tam_ruido = 100
tam_batch = 32
tam_img = 28
epocas_alvo = 5
epocas_gen = 1
learn_rate_alvo = 0.001
learn_rate_gen = 0.0001
dataset = "mnist"
partitioner = "Class" # 'Dir', 'IID' (IID no else)
alpha_dir = 0.1
agg = "f2a" # 'disc', 'full', 'f2a'
# num_chunks = 
model = "gen" # 'alvo', 'gen', 'both'
fid = false
teste = false
xgb_params.objective = "binary:logistic"
xgb_params.eta = 0.1 # Learning rate
xgb_params.max-depth = 8
xgb_params.eval-metric = "auc"
xgb_params.nthread = 16
xgb_params.num-parallel-tree = 1
xgb_params.subsample = 1
xgb_params.tree-method = "hist"

[tool.flwr.federations]
default = "local-simulation"

[tool.flwr.federations.local-simulation]
options.num-supernodes = 10
options.backend.client-resources.num-cpus = 1
options.backend.client-resources.num-gpus = 0.2

