[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "GeraFed"
version = "1.0.0"
description = "Data Augmentation para Dados Heterogêneos em Aprendizado Federado"
license = "Apache-2.0"
dependencies = [
    "flwr[simulation]>=1.12.0",
    "flwr-datasets[vision]>=0.3.0",
    "torch==2.2.1",
    "torchvision==0.17.1",
    "numpy<2.0"
]

[tool.hatch.build.targets.wheel]
packages = ["."]

[tool.flwr.app]
publisher = "gustavoguaragna"

[tool.flwr.app.components]
serverapp = "Simulation.TAB.server_app:app"
clientapp = "Simulation.TAB.client_app:app"

[tool.flwr.app.config]
num_rodadas = 10
fraction_fit_alvo = 1.0
fraction_fit_gen = 1.0
tam_ruido = 100
tam_batch = 64
tam_img = 28
epocas_alvo = 2
epocas_gen = 2
num_dadosssyn = 10
learn_rate_alvo = 0.001
learn_rate_gen = 0.0001
modelo_alvo = "mlp"
modelo_gen = "gan"
dataset = "mnist"
niid = true
alpha_dir = 0.1
agg = "full" # 'disc', 'full'
xgb_params.objective = "binary:logistic"
xgb_params.eta = 0.1 # Learning rate
xgb_params.max-depth = 8
xgb_params.eval-metric = "auc"
xgb_params.nthread = 16
xgb_params.num-parallel-tree = 1
xgb_params.subsample = 1
xgb_params.tree-method = "hist"

[tool.flwr.federations]
default = "local-simulation"

[tool.flwr.federations.local-simulation]
options.num-supernodes = 4
options.backend.client-resources.num-cpus = 1
options.backend.client-resources.num-gpus = 0

