# Use an official Python runtime as a parent image
FROM arm64v8/python:3.10-slim-buster

# Set the working directory in the container to /app
WORKDIR /app

# Adicionando arquivos cliente
ADD ./client.py .
ADD ./helpers/load_data.py .
ADD ./model/model.py .

# Copy the requirements file into the container
COPY ./requirements.txt /app/requirements.txt

# Install gcc, g++, and other dependencies
RUN apt-get update && apt-get install -y \
    gcc \
    python3-dev && \
    rm -rf /var/lib/apt/lists/*

# Install any needed packages specified in requirements.txt
RUN pip install -r requirements.txt

# Copy the rest of the application code
# COPY . /app

# Command to run the application
CMD ["python3", "-u", "client.py"]
